-- Migration 210: Location Relationships
-- Enables geographic expansion and neighborhood context

BEGIN;

-- Create locations table for neighborhoods/districts
CREATE TABLE IF NOT EXISTS locations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  parent_city TEXT NOT NULL,
  country TEXT NOT NULL,
  latitude FLOAT,
  longitude FLOAT,
  nearby_locations JSONB DEFAULT '[]'::jsonb,
  walking_time JSONB DEFAULT '{}'::jsonb,
  neighborhood_type TEXT,
  cultural_notes TEXT,
  description TEXT,
  embedding vector(3072),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_locations_parent ON locations(parent_city);
CREATE INDEX IF NOT EXISTS idx_locations_name ON locations(name);
CREATE INDEX IF NOT EXISTS idx_locations_embedding ON locations
  USING ivfflat (embedding vector_cosine_ops) WITH (lists = 200)
  WHERE embedding IS NOT NULL;

-- Seed Tokyo neighborhoods
INSERT INTO locations (name, parent_city, country, latitude, longitude, nearby_locations, walking_time, neighborhood_type, cultural_notes, description) VALUES
('Shibuya', 'Tokyo', 'Japan', 35.6595, 139.7004, '["Aoyama", "Omotesando", "Harajuku"]'::jsonb, '{"Aoyama": 10, "Omotesando": 8, "Harajuku": 5}'::jsonb, 'entertainment', 'Youth culture, nightlife, fashion', 'Shibuya: Tokyo''s vibrant youth and entertainment district. Known for the famous crossing, trendy cafes, nightlife, and fashion retail. Borders Aoyama (design district) to the south and Harajuku (street fashion) to the north.'),
('Aoyama', 'Tokyo', 'Japan', 35.6654, 139.7125, '["Shibuya", "Omotesando", "Roppongi"]'::jsonb, '{"Shibuya": 10, "Omotesando": 5, "Roppongi": 12}'::jsonb, 'design', 'Design district, high-end boutiques, art galleries', 'Aoyama: Tokyo''s design and fashion district. Tree-lined Omotesando Avenue connects to Shibuya (10 min walk). Known for architectural landmarks (Prada Tokyo, Dior Omotesando), contemporary art spaces, and refined dining. Quieter and more sophisticated than neighboring Shibuya.'),
('Omotesando', 'Tokyo', 'Japan', 35.6694, 139.7089, '["Aoyama", "Shibuya", "Harajuku"]'::jsonb, '{"Aoyama": 5, "Shibuya": 8, "Harajuku": 8}'::jsonb, 'luxury', 'Tokyo''s Champs-Élysées, luxury shopping', 'Omotesando: Tokyo''s premier luxury shopping boulevard. Wide, tree-lined avenue connecting Aoyama to Harajuku. Home to flagship stores of international luxury brands, contemporary architecture, and sophisticated dining. Often called Tokyo''s Champs-Élysées.'),
('Harajuku', 'Tokyo', 'Japan', 35.6711, 139.7028, '["Shibuya", "Omotesando", "Shibuya"]'::jsonb, '{"Shibuya": 5, "Omotesando": 8}'::jsonb, 'youth', 'Street fashion, youth culture, Takeshita Street', 'Harajuku: Tokyo''s epicenter of youth culture and street fashion. Takeshita Street draws crowds for its vibrant energy, quirky shops, and casual eats. Adjacent to Omotesando''s luxury boulevard, creating a fascinating contrast of styles.'),
('Shinjuku', 'Tokyo', 'Japan', 35.6938, 139.7034, '["Yoyogi", "Nakano", "Shibuya"]'::jsonb, '{"Yoyogi": 8, "Nakano": 10, "Shibuya": 12}'::jsonb, 'business', 'Business district, nightlife, department stores', 'Shinjuku: Tokyo''s major business and entertainment hub. Dense with skyscrapers, department stores, restaurants, and nightlife. The west side is corporate; the east side is vibrant and diverse. Gateway to many neighborhoods via major train lines.'),
('Ginza', 'Tokyo', 'Japan', 35.6717, 139.7645, '["Marunouchi", "Nihonbashi"]'::jsonb, '{"Marunouchi": 10, "Nihonbashi": 8}'::jsonb, 'luxury', 'Upscale shopping, fine dining, luxury brands', 'Ginza: Tokyo''s upscale shopping and dining district. Wide boulevards lined with luxury department stores, flagship boutiques, and Michelin-starred restaurants. Elegant and refined, especially striking on weekends when the main street becomes pedestrian-only.'),
('Roppongi', 'Tokyo', 'Japan', 35.6627, 139.7314, '["Aoyama", "Azabu", "Shibuya"]'::jsonb, '{"Aoyama": 12, "Azabu": 8, "Shibuya": 15}'::jsonb, 'nightlife', 'International district, nightlife, art museums', 'Roppongi: Tokyo''s international district, known for nightlife, art museums (Mori Art Museum, National Art Center), and a mix of expat-friendly restaurants. More international in character than other Tokyo neighborhoods.'),
('Daikanyama', 'Tokyo', 'Japan', 35.6484, 139.6997, '["Shibuya", "Naka-Meguro", "Ebisu"]'::jsonb, '{"Shibuya": 10, "Naka-Meguro": 5, "Ebisu": 8}'::jsonb, 'residential', 'Quiet, sophisticated, cafes and boutiques', 'Daikanyama: A quiet, sophisticated residential neighborhood known for its cafes, boutiques, and relaxed atmosphere. Less touristy than Shibuya but within walking distance. Favored by locals for its refined, low-key vibe.'),
('Naka-Meguro', 'Tokyo', 'Japan', 35.6441, 139.6977, '["Daikanyama", "Shibuya", "Ebisu"]'::jsonb, '{"Daikanyama": 5, "Shibuya": 12, "Ebisu": 6}'::jsonb, 'residential', 'Cherry blossoms, trendy cafes, residential charm', 'Naka-Meguro: Residential neighborhood famous for cherry blossoms along the Meguro River. Trendy cafes, small boutiques, and a relaxed residential feel. Popular with young professionals and families.'),
('Ebisu', 'Tokyo', 'Japan', 35.6467, 139.7101, '["Daikanyama", "Naka-Meguro", "Shibuya"]'::jsonb, '{"Daikanyama": 8, "Naka-Meguro": 6, "Shibuya": 10}'::jsonb, 'dining', 'Dining hub, izakayas, casual atmosphere', 'Ebisu: A dining hub known for its concentration of izakayas, casual restaurants, and bars. Popular with locals for after-work dining and drinks. More relaxed and less touristy than Shibuya.')
ON CONFLICT (name) DO NOTHING;

-- Seed Paris neighborhoods
INSERT INTO locations (name, parent_city, country, latitude, longitude, nearby_locations, walking_time, neighborhood_type, cultural_notes, description) VALUES
('Le Marais', 'Paris', 'France', 48.8570, 2.3622, '["Saint-Germain", "Bastille", "Hôtel de Ville"]'::jsonb, '{"Saint-Germain": 15, "Bastille": 10, "Hôtel de Ville": 8}'::jsonb, 'historic', 'Historic district, galleries, trendy boutiques', 'Le Marais: Historic district with narrow medieval streets, now a center for contemporary art galleries, trendy boutiques, and cafes. Jewish quarter, LGBTQ+ friendly, rich in history and culture.'),
('Saint-Germain', 'Paris', 'France', 48.8542, 2.3332, '["Le Marais", "Latin Quarter", "Louvre"]'::jsonb, '{"Le Marais": 15, "Latin Quarter": 12, "Louvre": 15}'::jsonb, 'intellectual', 'Literary cafés, publishing houses, classic bistros', 'Saint-Germain-des-Prés: The intellectual heart of Paris. Literary cafés (Les Deux Magots, Café de Flore), publishing houses, art galleries, and classic bistros. Once home to Sartre, de Beauvoir, and Hemingway.'),
('Montmartre', 'Paris', 'France', 48.8867, 2.3431, '["Pigalle", "Batignolles"]'::jsonb, '{"Pigalle": 8, "Batignolles": 12}'::jsonb, 'artistic', 'Historic artists'' quarter, Sacré-Cœur, charming streets', 'Montmartre: Historic artists'' quarter on a hill overlooking Paris. Home to Sacré-Cœur, charming cobblestone streets, and artist squares. Tourist-heavy but retains artistic character.'),
('Bastille', 'Paris', 'France', 48.8532, 2.3694, '["Le Marais", "Oberkampf", "Père Lachaise"]'::jsonb, '{"Le Marais": 10, "Oberkampf": 8, "Père Lachaise": 12}'::jsonb, 'vibrant', 'Nightlife, trendy bars, diverse dining', 'Bastille: Vibrant neighborhood around the historic Place de la Bastille. Known for nightlife, trendy bars, diverse dining options, and a young, energetic atmosphere.'),
('Latin Quarter', 'Paris', 'France', 48.8506, 2.3442, '["Saint-Germain", "Notre-Dame", "Louvre"]'::jsonb, '{"Saint-Germain": 12, "Notre-Dame": 8, "Louvre": 10}'::jsonb, 'academic', 'Student district, historic streets, affordable dining', 'Latin Quarter: Student district around the Sorbonne. Historic narrow streets, affordable dining, bookshops, and a lively academic atmosphere. Close to Notre-Dame and the Seine.'),
('Champs-Élysées', 'Paris', 'France', 48.8698, 2.3076, '["Madeleine", "Trocadéro", "Arc de Triomphe"]'::jsonb, '{"Madeleine": 8, "Trocadéro": 12, "Arc de Triomphe": 5}'::jsonb, 'tourist', 'Iconic avenue, shopping, grand hotels', 'Champs-Élysées: Paris''s most famous avenue, stretching from Place de la Concorde to Arc de Triomphe. Shopping, grand hotels, theaters, and tourist attractions. Busy and commercial but iconic.'),
('Pigalle', 'Paris', 'France', 48.8828, 2.3378, '["Montmartre", "SoPi"]'::jsonb, '{"Montmartre": 8, "SoPi": 10}'::jsonb, 'nightlife', 'Historic red-light district, vibrant nightlife', 'Pigalle: Historic red-light district transitioning into a vibrant nightlife and entertainment hub. Theaters, music venues, bars, and a mix of historic and modern character.')
ON CONFLICT (name) DO NOTHING;

-- Seed London neighborhoods
INSERT INTO locations (name, parent_city, country, latitude, longitude, nearby_locations, walking_time, neighborhood_type, cultural_notes, description) VALUES
('Soho', 'London', 'United Kingdom', 51.5146, -0.1339, '["Covent Garden", "Mayfair", "Fitzrovia"]'::jsonb, '{"Covent Garden": 8, "Mayfair": 10, "Fitzrovia": 8}'::jsonb, 'entertainment', 'Nightlife, restaurants, theaters, LGBTQ+ hub', 'Soho: London''s entertainment hub. Dense with restaurants, bars, theaters, and nightlife. LGBTQ+ friendly, diverse, and always buzzing. Historic red-light district now a cultural and culinary center.'),
('Covent Garden', 'London', 'United Kingdom', 51.5127, -0.1233, '["Soho", "Holborn", "Leicester Square"]'::jsonb, '{"Soho": 8, "Holborn": 10, "Leicester Square": 5}'::jsonb, 'tourist', 'Market, theaters, shopping, street performers', 'Covent Garden: Historic market area now a major tourist destination. Theaters, shopping, restaurants, and street performers. Lively and bustling, especially on weekends.'),
('Mayfair', 'London', 'United Kingdom', 51.5098, -0.1463, '["Soho", "Hyde Park", "Marylebone"]'::jsonb, '{"Soho": 10, "Hyde Park": 8, "Marylebone": 12}'::jsonb, 'luxury', 'Upscale shopping, fine dining, luxury hotels', 'Mayfair: London''s most exclusive neighborhood. Luxury shopping (Bond Street), fine dining, art galleries, and five-star hotels. Elegant and refined.'),
('Shoreditch', 'London', 'United Kingdom', 51.5227, -0.0814, '["Hoxton", "Hackney", "City"]'::jsonb, '{"Hoxton": 5, "Hackney": 10, "City": 12}'::jsonb, 'creative', 'Creative hub, street art, trendy bars, tech startups', 'Shoreditch: Creative hub known for street art, independent galleries, trendy bars, and tech startups. Hipster culture, vintage shops, and a vibrant nightlife scene.'),
('Marylebone', 'London', 'United Kingdom', 51.5183, -0.1489, '["Mayfair", "Regent''s Park", "Fitzrovia"]'::jsonb, '{"Mayfair": 12, "Regent''s Park": 8, "Fitzrovia": 8}'::jsonb, 'residential', 'Village feel, independent shops, good restaurants', 'Marylebone: Residential neighborhood with a village feel. Independent shops, cafes, good restaurants, and proximity to Regent''s Park. Less touristy, more local.'),
('Notting Hill', 'London', 'United Kingdom', 51.5158, -0.1962, '["Kensington", "Holland Park", "Bayswater"]'::jsonb, '{"Kensington": 10, "Holland Park": 8, "Bayswater": 8}'::jsonb, 'residential', 'Portobello Road Market, colorful houses, cafes', 'Notting Hill: Charming residential neighborhood famous for Portobello Road Market, colorful houses, and independent cafes. Quieter than central London, with a bohemian character.'),
('Camden', 'London', 'United Kingdom', 51.5390, -0.1426, '["Regent''s Park", "King''s Cross", "Hampstead"]'::jsonb, '{"Regent''s Park": 12, "King''s Cross": 10, "Hampstead": 15}'::jsonb, 'alternative', 'Alternative culture, markets, music venues', 'Camden: Alternative culture hub with famous markets, music venues, and eclectic shops. Youthful energy, diverse dining, and a strong counterculture identity.')
ON CONFLICT (name) DO NOTHING;

-- Seed New York neighborhoods
INSERT INTO locations (name, parent_city, country, latitude, longitude, nearby_locations, walking_time, neighborhood_type, cultural_notes, description) VALUES
('SoHo', 'New York', 'United States', 40.7231, -74.0026, '["Tribeca", "West Village", "Nolita"]'::jsonb, '{"Tribeca": 8, "West Village": 12, "Nolita": 5}'::jsonb, 'shopping', 'Historic cast-iron architecture, art galleries, shopping', 'SoHo: Historic district known for cast-iron architecture, art galleries, high-end shopping, and dining. Once an artists'' enclave, now upscale and commercial but retains architectural charm.'),
('West Village', 'New York', 'United States', 40.7336, -74.0027, '["SoHo", "Greenwich Village", "Chelsea"]'::jsonb, '{"SoHo": 12, "Greenwich Village": 5, "Chelsea": 15}'::jsonb, 'residential', 'Charming streets, brownstones, restaurants, LGBTQ+ history', 'West Village: Charming residential neighborhood with tree-lined streets, brownstones, and excellent restaurants. Historic LGBTQ+ hub, intimate atmosphere, and a village feel in the heart of Manhattan.'),
('Tribeca', 'New York', 'United States', 40.7187, -74.0086, '["SoHo", "Financial District", "Chinatown"]'::jsonb, '{"SoHo": 8, "Financial District": 10, "Chinatown": 12}'::jsonb, 'residential', 'Converted lofts, upscale dining, family-friendly', 'Tribeca: Upscale residential neighborhood in converted industrial lofts. Excellent dining, family-friendly, and quiet compared to neighboring SoHo. Popular with celebrities and families.'),
('Nolita', 'New York', 'United States', 40.7215, -73.9953, '["SoHo", "East Village", "Little Italy"]'::jsonb, '{"SoHo": 5, "East Village": 10, "Little Italy": 5}'::jsonb, 'boutique', 'Boutique shopping, small cafes, trendy', 'Nolita: Small neighborhood between SoHo and Little Italy. Boutique shopping, small cafes, trendy but less commercial than SoHo. Intimate and walkable.'),
('East Village', 'New York', 'United States', 40.7272, -73.9846, '["Nolita", "Lower East Side", "Greenwich Village"]'::jsonb, '{"Nolita": 10, "Lower East Side": 8, "Greenwich Village": 8}'::jsonb, 'nightlife', 'Historic punk scene, bars, diverse dining, nightlife', 'East Village: Historic counterculture hub, once home to punk rock. Bars, diverse dining, nightlife, and a bohemian character. More affordable and less polished than West Village.'),
('Chelsea', 'New York', 'United States', 40.7470, -74.0018, '["West Village", "Flatiron", "Meatpacking"]'::jsonb, '{"West Village": 15, "Flatiron": 10, "Meatpacking": 8}'::jsonb, 'art', 'Art galleries, High Line, design stores', 'Chelsea: Art gallery district known for its concentration of contemporary art galleries. The High Line park, design stores, and proximity to Meatpacking District make it a cultural destination.'),
('Meatpacking District', 'New York', 'United States', 40.7420, -74.0079, '["Chelsea", "West Village", "SoHo"]'::jsonb, '{"Chelsea": 8, "West Village": 12, "SoHo": 15}'::jsonb, 'nightlife', 'Nightlife, trendy restaurants, High Line access', 'Meatpacking District: Former industrial area transformed into a trendy nightlife and dining destination. High-end restaurants, bars, and access to the High Line. Glamorous and energetic.'),
('Greenwich Village', 'New York', 'United States', 40.7331, -74.0029, '["West Village", "East Village", "SoHo"]'::jsonb, '{"West Village": 5, "East Village": 8, "SoHo": 10}'::jsonb, 'historic', 'Historic bohemian quarter, NYU area, Washington Square', 'Greenwich Village: Historic bohemian quarter, home to NYU and Washington Square Park. Cafes, bookshops, jazz clubs, and a rich cultural history. Mix of students, residents, and tourists.')
ON CONFLICT (name) DO NOTHING;

-- Seed Los Angeles neighborhoods
INSERT INTO locations (name, parent_city, country, latitude, longitude, nearby_locations, walking_time, neighborhood_type, cultural_notes, description) VALUES
('Hollywood', 'Los Angeles', 'United States', 34.0928, -118.3287, '["West Hollywood", "Los Feliz", "Griffith Park"]'::jsonb, '{"West Hollywood": 15, "Los Feliz": 12, "Griffith Park": 20}'::jsonb, 'entertainment', 'Iconic landmarks, Walk of Fame, entertainment industry', 'Hollywood: Iconic entertainment district known for the Walk of Fame, theaters, and historic landmarks. Tourist-heavy but central to LA''s entertainment industry. More walkable than many LA neighborhoods.'),
('West Hollywood', 'Los Angeles', 'United States', 34.0900, -118.3617, '["Hollywood", "Beverly Hills", "Fairfax"]'::jsonb, '{"Hollywood": 15, "Beverly Hills": 10, "Fairfax": 8}'::jsonb, 'nightlife', 'Nightlife, LGBTQ+ hub, Sunset Strip, dining', 'West Hollywood: Vibrant nightlife hub and LGBTQ+ center. Sunset Strip, excellent dining, and a lively atmosphere. More walkable and dense than typical LA neighborhoods.'),
('Beverly Hills', 'Los Angeles', 'United States', 34.0736, -118.4004, '["West Hollywood", "Bel-Air", "Century City"]'::jsonb, '{"West Hollywood": 10, "Bel-Air": 8, "Century City": 8}'::jsonb, 'luxury', 'Luxury shopping (Rodeo Drive), fine dining, luxury hotels', 'Beverly Hills: Iconic luxury destination. Rodeo Drive shopping, fine dining, and luxury hotels. Elegant and refined, though less walkable than urban centers.'),
('Santa Monica', 'Los Angeles', 'United States', 34.0195, -118.4912, '["Venice", "Brentwood", "Pacific Palisades"]'::jsonb, '{"Venice": 8, "Brentwood": 10, "Pacific Palisades": 12}'::jsonb, 'coastal', 'Beach, pier, shopping, dining, pedestrian-friendly', 'Santa Monica: Beach city with a pedestrian-friendly downtown. Third Street Promenade shopping, pier, beach access, and excellent dining. One of LA''s most walkable areas.'),
('Venice', 'Los Angeles', 'United States', 33.9850, -118.4695, '["Santa Monica", "Marina del Rey", "Culver City"]'::jsonb, '{"Santa Monica": 8, "Marina del Rey": 5, "Culver City": 12}'::jsonb, 'bohemian', 'Bohemian vibe, beach, canals, skate culture, Abbot Kinney', 'Venice: Bohemian beach neighborhood known for canals, skate culture, Abbot Kinney Boulevard shopping, and a relaxed, creative atmosphere. Mix of beach culture and artistic character.'),
('Los Feliz', 'Los Angeles', 'United States', 34.1083, -118.2883, '["Hollywood", "Silver Lake", "Griffith Park"]'::jsonb, '{"Hollywood": 12, "Silver Lake": 8, "Griffith Park": 5}'::jsonb, 'residential', 'Residential, cafes, Griffith Park access, hipster vibe', 'Los Feliz: Residential neighborhood with cafes, restaurants, and easy access to Griffith Park. Hipster vibe, independent shops, and a more relaxed pace than Hollywood.'),
('Silver Lake', 'Los Angeles', 'United States', 34.0867, -118.2702, '["Los Feliz", "Echo Park", "Atwater Village"]'::jsonb, '{"Los Feliz": 8, "Echo Park": 5, "Atwater Village": 8}'::jsonb, 'creative', 'Creative hub, hipster culture, cafes, music scene', 'Silver Lake: Creative hub known for hipster culture, independent cafes, music venues, and a vibrant arts scene. Hilly streets, trendy restaurants, and a bohemian character.')
ON CONFLICT (name) DO NOTHING;

COMMIT;

