-- Add AI-generated fields to destinations table
-- These fields are generated by the generate_ai_fields.py script using Google Gemini

DO $$ BEGIN
  -- Vibe tags: Array of atmosphere/style tags (e.g., ["romantic", "modern", "cozy"])
  ALTER TABLE destinations ADD COLUMN IF NOT EXISTS vibe_tags TEXT[];
  
  -- Keywords: Array of SEO keywords (e.g., ["restaurant", "tokyo", "fine-dining"])
  ALTER TABLE destinations ADD COLUMN IF NOT EXISTS keywords TEXT[];
  
  -- Short summary: AI-generated 2-3 sentence summary
  ALTER TABLE destinations ADD COLUMN IF NOT EXISTS short_summary TEXT;
  
  -- Search keywords: Natural language search phrases (e.g., ["romantic restaurant tokyo", "best cafe paris"])
  ALTER TABLE destinations ADD COLUMN IF NOT EXISTS search_keywords TEXT[];
  
  -- Timestamp for when AI fields were generated
  ALTER TABLE destinations ADD COLUMN IF NOT EXISTS ai_fields_generated_at TIMESTAMP WITH TIME ZONE;
EXCEPTION WHEN others THEN NULL; END $$;

-- Create indexes for better search performance
CREATE INDEX IF NOT EXISTS idx_destinations_vibe_tags ON destinations USING GIN(vibe_tags);
CREATE INDEX IF NOT EXISTS idx_destinations_keywords ON destinations USING GIN(keywords);
CREATE INDEX IF NOT EXISTS idx_destinations_search_keywords ON destinations USING GIN(search_keywords);
CREATE INDEX IF NOT EXISTS idx_destinations_ai_fields_generated_at ON destinations(ai_fields_generated_at DESC);
